"""Fixtures shared by the test files.

The ledger vault lives here rather than in one test file because two of them need a *real* vault — the
adapter's own tests, and the example that plays with one — and a second, thinner vault shape written for the
second file would be a fixture that drifts from the format it is meant to stand for.
"""
from __future__ import annotations

import pytest


STATE_MD = """# STATE — session digest

<!-- GENERATED by `ledger-state generate` — never hand-edit. -->

_Regenerated: 2026-09-21T09:00:00Z_

## Standing params
- **Core:** 2.0.3 (locked, verified 2026-09-21)
- **Push policy:** push to main after each commit
- Full params: `memory/workflows/active.md`

## Office — who's in, right now
- **Priya** (S014) — Working — Phase 3 orientation

## Current task
- **2026-09-21 — Priya / claude-sonnet-5** — widen the beam beyond one — *in-progress*

## Backlog — High priority (the top of the queue)
(none)

_1 medium, 0 low priority row(s) — see tasks/backlog.md_

## Logs at a glance — open only if your task touches these
- inefficiencies/log.md (project code/env friction): 1 entry, last added 2026-09-14
"""

ROSTER_MD = """# Team Roster (current office — update in place)

<!-- TEMPLATE — one row per person in this office:
| <Name> | S<NNN> | <model id> | <what you're doing> | Working | <stage reached / shipped outcome / blocker> |
-->

| Name | Codename | Model | Doing | Status | Status detail |
|------|----------|-------|-------|--------|---------------|
| Priya | S014 | claude-sonnet-5 | widening the beam | Working | Phase 3 orientation, State.md read |
"""

SESSIONS_MD = """# Agent Sessions (append-only within the current office)

<!-- TEMPLATE — copy below the last entry and FILL IN every placeholder:
---
## YYYY-MM-DD — Session N
- **Agent:** <name> | **Model:** <model id> | **Platform:** <machine/sandbox + OS> | **Role:** <engineer, or overlay from .context_ledger/core/roles/> | **Core:** <version from .context_ledger/core/VERSION>
- **Task:** <what this session set out to do>
- **Commits:** <count> (<first-sha>..<last-sha>)
- **Outcome:** <done / partial / blocked — one line>
- **Open items:** <pointers into tasks/backlog.md (actionable) or tasks/parking-lot.md (findings/questions), or "none">
- **Notes:** .context_ledger/memory/office/sessions/<date>-<N>/notes.md  (or "none")
- **Report:** .context_ledger/memory/office/reviews/YYYY-MM-DD-review.md
-->

## 2026-09-14 — Session 10
- **Agent:** Amari | **Model:** qwen3.8-flash | **Platform:** Windows 11 (local) | **Core:** 1.1.1
- **Task:** README front-door rewrite
- **Commits:** 5 (f1fb139..bffbe9b)
- **Outcome:** done — README rewritten around the amnesia problem
- **Open items:** none
- **Notes:** summary only

## 2026-09-21 — Session 14
- **Agent:** Priya | **Model:** claude-sonnet-5 | **Platform:** macOS 24.6.0 (local) | **Core:** 2.0.3
- **Task:** widen the beam beyond one
- **Commits:** 2 (3e9d5c5..5796d66)
- **Outcome:** partial — the interface is in, the second strategy is not
- **Open items:** B-2026-09-21-4 — design the second strategy
- **Notes:** .context_ledger/memory/office/sessions/2026-09-21-14/notes.md
"""

CURRENT_MD = """# Current Task (overwrite each session)

<!-- TEMPLATE — replace everything below this comment:
- **Session:** YYYY-MM-DD — <agent> / <model>
- **Task:** <what is being worked on right now>
- **Status:** in-progress | done | blocked (<blocker>)
-->

- **Session:** 2026-09-21 — Priya / claude-sonnet-5
- **Task:** widen the beam beyond one — the search strategy interface
- **Status:** in-progress
"""

BACKLOG_MD = """# Backlog (capped work queue — actionable rows only)

<!-- TEMPLATE — add one row to the matching priority table:
| B-<YYYY-MM-DD>-<n> | <what to do> |
-->

## Open Items

### High Priority

| ID | Summary |
|----|---------|
| B-2026-09-14-1 | Self-host the vault in this repo |
| B-2026-09-21-4 | Design the second search strategy |

### Medium Priority

| ID | Summary |
|----|---------|
| B-2026-09-02-3 | Persisted state so a run can resume |

### Low Priority

| ID | Summary |
|----|---------|
"""

PARKING_MD = """# Parking Lot (deferred knowledge — not a queue)

<!-- TEMPLATE — add one row to the matching section:
| P-<YYYY-MM-DD>-<n> | <enough context that a future session can pick
      this up cold — status qualifiers in the text; promote to the
      backlog when it becomes actionable> |
-->

## Findings

| ID | Summary |
|----|---------|
| P-2026-09-22-1 | A whole-tree manifest forces one core change per release |

## Open questions

| ID | Summary |
|----|---------|

## Deferred work

| ID | Summary |
|----|---------|

## Someday

| ID | Summary |
|----|---------|
"""

DECISIONS_MD = """# Architectural Decisions (append-only, ADR-style)

<!-- TEMPLATE — copy below the last entry:
---
## ADR-N: <short title> (YYYY-MM-DD)
- **Status:** accepted | superseded by ADR-M
- **Context:** <what forced the decision>
-->

## ADR-2: The parking lot is not a queue (2026-08-15)
- **Status:** accepted
- **Context:** a 57-row backlog was unworkable
- **Decision:** the backlog is a capped queue; findings live in the parking lot
- **Consequences:** nothing is lost, but two files must be kept honest

## ADR-7: Common Pitfalls stays inline (2026-09-18)
- **Status:** accepted
- **Context:** routing weak agents to a separate playbook failed
- **Decision:** keep the pitfalls inline in both editions
- **Consequences:** the two editions number that section differently
"""

INEFFICIENCIES_MD = """# Inefficiency Log (append-only — real friction only)

<!-- TEMPLATE — copy below the last entry:
---
## YYYY-MM-DD — <agent> / <model>
- **Problem:** <what went wrong or was slower than it should be>
- **Cost:** <rough time/effort wasted>
- **Workaround / fix:** <what worked, or "unresolved">
- **Upstream:** candidate  ← add this line ONLY for protocol-level friction
-->
"""

INEFFICIENCIES_ENTRY = """
## 2026-09-14 — Leo / claude-sonnet-5
- **Problem:** three PowerShell / Git-Bash traps in one release
- **Cost:** ~25 minutes lost
- **Cause:** two shell ports of the same tool, drifting
- **Workaround / fix:** probe the port that carries the flaw, one variable at a time
- **Prevent next time:** keep one core change in flight at a time
"""

NOTES_MD = """# Session Notes: YYYY-MM-DD — Session N

<!-- TEMPLATE — copy below the last entry:
---
## YYYY-MM-DD — <agent> / <model> (Session N)
<findings, attempts, dead ends — session-scoped detail.>
-->
"""


@pytest.fixture()
def project(tmp_path):
    """A bootstrapped vault, in the real shapes."""
    led = tmp_path / ".context_ledger"
    office = led / "memory" / "office"
    (led / "core").mkdir(parents=True)
    (led / "core" / "VERSION").write_text("2.0.3\n")
    for sub in ("agents", "tasks", "plans", "flaws", "inefficiencies", "sessions", "reviews"):
        (office / sub).mkdir(parents=True)
    (office / "STATE.md").write_text(STATE_MD)
    (office / "agents" / "roster.md").write_text(ROSTER_MD)
    (office / "agents" / "sessions.md").write_text(SESSIONS_MD)
    (office / "tasks" / "current.md").write_text(CURRENT_MD)
    (office / "tasks" / "backlog.md").write_text(BACKLOG_MD)
    (office / "tasks" / "parking-lot.md").write_text(PARKING_MD)
    (office / "plans" / "decisions.md").write_text(DECISIONS_MD)
    (office / "flaws" / "log.md").write_text("# Flaws (append-only)\n\n<!-- no entries yet -->\n")
    (office / "inefficiencies" / "log.md").write_text(INEFFICIENCIES_MD + INEFFICIENCIES_ENTRY)
    (office / "sessions" / "notes.md").write_text(NOTES_MD)
    (led / "memory" / "user").mkdir()
    (led / "memory" / "user" / "preferences.md").write_text(
        "- **Prefers:** terse reports, no confirmation prompts on default next steps\n")
    (led / "history").mkdir()
    (led / "history" / "office-001.md").write_text(
        "# Office 001 — permanent record\n\n- **Recurring:** the tests were flaky before the harness fix\n")
    return tmp_path
